export default function Head() {
  return (
    <>
      <title>Content ERP Version 1.0.0.1</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Jack" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
